/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define AUDIORESAMPLE_FORMAT_AUTO

#undef CDPARANOIA_HEADERS_IN_DIR

#define DEFAULT_AUDIOSINK "autoaudiosink"

#define DEFAULT_VIDEOSINK "autovideosink"

#define GETTEXT_PACKAGE "gst-plugins-base-1.0"

#define GIO_LIBDIR "/usr/lib/x86_64-linux-gnu"

#define GIO_MODULE_DIR "/usr/lib/x86_64-linux-gnu/gio/modules"

#define GIO_PREFIX "/usr"

#define GST_API_EXPORT extern __attribute__ ((visibility ("default")))

#define GST_API_VERSION "1.0"

#define GST_DATADIR "/usr/share"

#define GST_INSTALL_PLUGINS_HELPER "/usr/lib/x86_64-linux-gnu/gst-install-plugins-helper"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer Base Plug-ins source release"

#define GST_PACKAGE_ORIGIN "https://gstreamer.freedesktop.org"

#define HAVE_DCGETTEXT 1

#define HAVE_DLFCN_H 1

#define HAVE_EMMINTRIN_H 1

#define HAVE_GIO_UNIX_2_0

#define HAVE_GMTIME_R 1

#define HAVE_INTTYPES_H 1

#define HAVE_ISO_CODES

#define HAVE_LINUX_DMA_BUF_H 1

#define HAVE_LOG2 1

#define HAVE_LRINTF 1

#define HAVE_MEMORY_H 1

#define HAVE_MMAP 1

#define HAVE_OGG

#define HAVE_ORC 1

#define HAVE_SMMINTRIN_H 1

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_WAIT_H 1

#define HAVE_THEORA

#define HAVE_UNISTD_H 1

#define HAVE_VORBIS_SYNTHESIS_RESTART

#define HAVE_X

#define HAVE_XMMINTRIN_H 1

#define HAVE_XSHM

#define HAVE_XVIDEO

#define HAVE_ZLIB

#define ISO_CODES_PREFIX "/usr"

#define ISO_CODES_VERSION "3.79"

#define LIBVISUAL_PLUGINSBASEDIR "/usr/lib/x86_64-linux-gnu/libvisual-0.4"

#define LOCALEDIR "/usr/share/locale"

#define PACKAGE "gst-plugins-base"

#define PACKAGE_VERSION "1.16.2"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOIDP 8

#define VERSION "1.16.2"

