#define VTPL_VERSION "0.0.0.prod0"
#define VTPL_DESCRIPTION "Communicate with Vtpl Vms"
#define VTPL_LICENSE "Proprietary"
#define VTPL_PACKAGE_NAME "Vtpl VMS plugins"
#define VTPL_PACKAGE_ORIGIN "https://videonetics.com"
